apiVersion: v1
kind: Service
metadata:
  name: transact-web
  namespace: transact
  labels:
    app.kubernetes.io/name: transact-web
    app.kubernetes.io/part-of: transact
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: transact-web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
